### ISSUE TITLE
[Bug]:  python webserver/main.py  No module named 'webserver'

### ISSUE THREAD

**Issue by pq784844602** [KylinMountain/graphrag-server#12]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

PS D:\www\graphrag-server> python webserver/main.py
Traceback (most recent call last):
  File "D:\www\graphrag-server\webserver\main.py", line 25, in <module>
    from webserver import gtypes
ModuleNotFoundError: No module named 'webserver'

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by KylinMountain** [comment]
1. 你有用conda建立虚拟环境吗？
2. 依赖都装好了么？

**Comment by KylinMountain** [comment]
试试
pip uninstall graphrag
然后
python -m webserver.main
试试

**Comment by KylinMountain** [comment]
No reponse
