### ISSUE TITLE
[Issue]: <title> 微调promot的参数改了吗

### ISSUE THREAD

**Issue by kiroo92** [KylinMountain/graphrag-server#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

```
usage: python -m graphrag.prompt_tune [-h] --config CONFIG [--root ROOT] [--domain DOMAIN] [--selection-method {all,random,top,auto}] [--n_subset_max N_SUBSET_MAX] [--k K] [--limit LIMIT]
                                      [--max-tokens MAX_TOKENS] [--min-examples-required MIN_EXAMPLES_REQUIRED] [--chunk-size CHUNK_SIZE] [--language LANGUAGE] [--no-entity-types] [--output OUTPUT]
python -m graphrag.prompt_tune: error: the following arguments are required: --config

```

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by KylinMountain** [comment]
确实官方改了 要看看参数是啥了
