### ISSUE TITLE
引用对应错误

### ISSUE THREAD

**Issue by zczlr12** [KylinMountain/graphrag-server#5]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

感觉References里面的id对应不上，好像应该对应Entity对象里的short_id

### Entity (1) 相关回答

![屏幕截图(812)](https://github.com/user-attachments/assets/0850d4e9-8a83-4465-85e7-56b421623629)

### 原代码结果

![屏幕截图(813)](https://github.com/user-attachments/assets/a591a734-c333-4967-be2f-3080109fefca)

### 尝试修改并添加Title

![屏幕截图(814)](https://github.com/user-attachments/assets/2f187906-0304-4263-b169-5f00cf15e885)

#### Entity.title

![屏幕截图(815)](https://github.com/user-attachments/assets/00451f48-0e58-42c5-867a-f9ed5d0eacc8)

### 修改结果

![屏幕截图(816)](https://github.com/user-attachments/assets/19f88d5b-db65-440c-b541-1f8318612e0b)

![屏幕截图(817)](https://github.com/user-attachments/assets/dd4be762-57d7-4112-ae78-e6f23abf3656)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: v0.2.0
- Operating System: Windows 11
- Python Version: 3.12.4
- Related Issues: References

**Comment by KylinMountain** [comment]
感谢 我会详细看一下

**Comment by KylinMountain** [comment]
@zczlr12 Thanks, 我已经修复了，包括其他实体或者关系的错误引用问题。若遇到其他bug，欢迎再次提交或者提PR
