### ISSUE TITLE
[Issue]: 硬编码的datatype

### ISSUE THREAD

**Issue by RedwindA** [KylinMountain/graphrag-server#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

webserver/main.py
```
    if datatype not in ["entities", "claims", "sources", "reports", "relationships"]:
        raise HTTPException(status_code=404, detail=f"{datatype} not found")
```
这里写死了datatype，如果使用自定义实体列表貌似会404？这样设计的目的是为了避免LLM生成虚假引用吗？从对应的index里动态获取实体类型会不会更好一点

**Comment by KylinMountain** [comment]
不会呀 自定义实体列表你的类型也还是entitiy呀？

**Comment by KylinMountain** [comment]
就好比 类型和实例的关系，你的自定义实体列表 其实是实例，它的类型是entity，这一点是不会变的。
