### ISSUE TITLE
[Bug]: 流式传输的时候经常卡在最后生成参考链接的部分

### ISSUE THREAD

**Issue by RedwindA** [KylinMountain/graphrag-server#9]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by KylinMountain** [comment]
这个我没遇到 有具体的视频参考吗？你是怎么用graphrag的呢？拷贝webserver到官方graphrag？这样是会卡住的。

**Comment by KylinMountain** [comment]
你要进微信群讨论吗？首页公众号 后台回复进群即可

**Comment by KylinMountain** [comment]
pip uninstall graphrag
然后
python -m webserver.main
试试
